# Generated by Django 4.1.3 on 2023-02-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="producto",
            name="amount",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="producto",
            name="productoName",
            field=models.CharField(max_length=50),
        ),
    ]
