# Generated by Django 4.1.3 on 2023-02-22 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0002_client_phone_producto_amount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetailSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("price_unit", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api_app.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api_app.client"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        through="api_app.DetailSale", to="api_app.producto"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="ventaproducto",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="ventaproducto",
            name="venta",
        ),
        migrations.DeleteModel(
            name="Venta",
        ),
        migrations.DeleteModel(
            name="VentaProducto",
        ),
        migrations.AddField(
            model_name="detailsale",
            name="sale",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api_app.sale"
            ),
        ),
        migrations.AddIndex(
            model_name="detailsale",
            index=models.Index(
                fields=["product"], name="api_app_det_product_b51c4d_idx"
            ),
        ),
    ]
